log_level: info
service_name: tedge-container-monitor

filter:
  include:
    names: []
    ids: []
    labels: []
    types: []
  exclude:
    names: ["^buildx.*"]
    labels: []

client:
  key: /etc/tedge/device-certs/local-tedge.key
  cert_file: /etc/tedge/device-certs/local-tedge.crt

  mqtt:
    host: 127.0.0.1
    port: 8883

  c8y:
    host: 127.0.0.1
    port: 8001

metrics:
  enabled: true
  interval: "300s"

events:
  enabled: true

delete_from_cloud:
  enabled: true
